#FROM node:16.16.0 AS  frontend
FROM node:14-alpine AS frontend
WORKDIR /app

# COPY package.json package-lock.json /app/
# ADD /bundles-src/ /app/bundles-src/
COPY bundles-src bundles-src
COPY package.json package.json
COPY package-lock.json package-lock.json
#COPY . .

RUN npm ci --dev
RUN ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
