version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14.6-alpine
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    container_name: web
    build:
      context: ../.
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    volumes:
      - ../.:/app
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

volumes:
  postgres_data:
