# Generated by Django 3.2.15 on 2023-05-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='выбранный ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CA', 'Наличными'), ('EP', 'Электронный')], db_index=True, default='EP', max_length=15, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RA', 'Необработанный'), ('PO', 'Заказа собирается'), ('DL', 'Доставка'), ('OC', 'Заказ выполнен')], db_index=True, default='RA', max_length=15, verbose_name='статус'),
        ),
    ]
